// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYkYO99qF3sB7lzLzWhvLCcVzTPPFuPtA',
    appId: '1:334432646239:web:6b663fe83e103d6065d7ea',
    messagingSenderId: '334432646239',
    projectId: 'fantasy-league-test',
    authDomain: 'fantasy-league-test.firebaseapp.com',
    databaseURL: 'https://fantasy-league-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fantasy-league-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgtvD8WHVfx6QLASibKrYJyBJu_Fq43SU',
    appId: '1:334432646239:android:66b9af567177759e65d7ea',
    messagingSenderId: '334432646239',
    projectId: 'fantasy-league-test',
    databaseURL: 'https://fantasy-league-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fantasy-league-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVX7SAsqEJ22UU4MQ1IerKZhRcgNCbbm8',
    appId: '1:334432646239:ios:c1358c5667298ade65d7ea',
    messagingSenderId: '334432646239',
    projectId: 'fantasy-league-test',
    databaseURL: 'https://fantasy-league-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fantasy-league-test.appspot.com',
    iosClientId: '334432646239-91har6nd4escdgda6ggtb2bhh40gitct.apps.googleusercontent.com',
    iosBundleId: 'com.example.fantasyAppAgneepath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVX7SAsqEJ22UU4MQ1IerKZhRcgNCbbm8',
    appId: '1:334432646239:ios:07f998f109c7168065d7ea',
    messagingSenderId: '334432646239',
    projectId: 'fantasy-league-test',
    databaseURL: 'https://fantasy-league-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fantasy-league-test.appspot.com',
    iosClientId: '334432646239-8522una21nvca01acsqq2mbu3qc02lmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fantasyAppAgneepath.RunnerTests',
  );
}
